#pragma once

#define MC_BLEND_CUBE_SCALE 2.f

#define MC_CHUNk_SIZE 8.f
#define MC_CHUNk_BLEND_SIZE MC_CHUNk_SIZE * MC_BLEND_CUBE_SCALE

#define MC_MAP_SIZE_X 5
#define MC_MAP_SIZE_Y 5
#define MC_MAP_RENDER_DISTANCE 10

#define MC_WATER_HEIGHT -10.f

#define MC_DIRT_LAYER 1
#define MC_GRASS_LAYER 2
#define MC_WATER_LAYER 3
#define MC_WATER_UP_LAYER 4
#define MC_LOG_LAYER 5
#define MC_LEAF_LAYER 6
#define MC_STONE_LAYER 7
#define MC_BEDROCK_LAYER 8
